version : '3'
services:
  #client API to send json data from mysql database
  product-api-service:
    build: ./product-api
    container_name: Web-Framework
    volumes:
      - ./product-api:/usr/src/app
    expose:
      - 5001
    depends_on:
      - db-mysql

  #web server 1 apache which uses files from website1 on port 8081
  website1:
    image: php:apache
    container_name: website1
    volumes:
      - ./website1:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - product-api-service
  
  #web server 2 apache which uses files from website1 on port 8082
  website2:
    image: php:apache
    container_name: website2
    volumes:
        - ./website1:/var/www/html
    ports:
        - 8082:80
    depends_on:
        - product-api-service

  #web server 3 apache which uses files from website1 on port 8083
  website3:
    image: php:apache
    container_name: website3
    volumes:
        - ./website1:/var/www/html
    ports:
        - 8083:80
    depends_on:
        - product-api-service

  #python admin API to read and write data from database
  product-api-service-admin:
    build: ./product-api-admin
    container_name: Web-Framework-Admin
    volumes:
      - ./product-api-admin:/usr/src/app
    expose:
      - 5000
    depends_on:
      - db-mysql

  #web server admin apache which is used for /admin and uses a different php pages to be able to add data to database
  website-admin:
    image: php:apache
    container_name: website-admin
    volumes:
        - ./website-admin:/var/www/html/admin
    ports:
        - 8080:80
    depends_on:
        - product-api-service-admin

  #mysql database that uses database folder with read only permission in the container directory
  db-mysql:
    image: mysql
    container_name: Database
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

  #proxy to redirect correctly all the websites
  haproxy:
    build: ./haproxy
    container_name: HAProxy
    ports: 
        - 80:80
    depends_on:
        - website1
        - website2
        - website3
        - website-admin