version : '3'
services:
  product-api-service:
    build: ./product-api
    container_name: Web-Framework
    volumes:
      - ./product-api:/usr/src/app
    expose:
      - 5001
    depends_on:
      - db-mysql

  website1:
    image: php:apache
    container_name: website1
    volumes:
      - ./website1:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - product-api-service
  
  website2:
    image: php:apache
    container_name: website2
    volumes:
        - ./website2:/var/www/html
    ports:
        - 8082:80
    depends_on:
        - product-api-service

  website3:
    image: php:apache
    container_name: website3
    volumes:
        - ./website3:/var/www/html
    ports:
        - 8083:80
    depends_on:
        - product-api-service

  product-api-service-admin:
    build: ./product-api-admin
    container_name: Web-Framework-Admin
    volumes:
      - ./product-api-admin:/usr/src/app
    expose:
      - 5000
    depends_on:
      - db-mysql

  website-admin:
    image: php:apache
    container_name: website-admin
    volumes:
        - ./website-admin:/var/www/html/admin
    ports:
        - 8080:80
    depends_on:
        - product-api-service-admin

  db-mysql:
    image: mysql
    container_name: Database
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

  haproxy:
    build: ./haproxy
    container_name: HAProxy
    ports: 
        - 80:80
    depends_on:
        - website1